development:
  secret_key_base: 'use rake secret to gerenate a secure secret key, copy and paste here'

test:
  secret_key_base: 'use rake secret to gerenate a secure secret key, copy and paste here'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
